### ISSUE TITLE
Crash after opening camera for scanning

### ISSUE THREAD

**Issue by OgunwoleOluwatobi** [Jumio/mobile-flutter#35]
**Describe the bug**
After clicking the verification and the camera is launched the process crashing and I get this error log

`java.lang.NoSuchMethodError: no static method "Lcom/jumio/jvision/jvcorejava/swig/JVCoreJavaJNI;.SwigDirector_FrameProcessor_pushFrame(Lcom/jumio/jvision/jvcorejava/swig/FrameProcessor;IJ)V"
                                                                                                    	at com.jumio.jvision.jvcorejava.swig.JVCoreJavaJNI.swig_module_init(Native Method)
                                                                                                    	at com.jumio.jvision.jvcorejava.swig.JVCoreJavaJNI.<clinit>(Unknown Source:0)
                                                                                                    	at jh.a.<clinit>(ImageFormat.java:1)
                                                                                                    	at cg.b$c.run(ExtractionClient.java:5)`

**Comment by OgunwoleOluwatobi** [comment]
The solution to this was to add jumio to the proguard file to keep the neccessary methods

**Comment by kolphi** [comment]
@OgunwoleOluwatobi Thank you very much for posting your solution. We'll re-test that and incorporate it into our upcoming 4.3.0 release if possible.
